export const initialLog = [
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
  "Initializing build...",
  "Fetching dependencies...",
  "Building project...",
  "Running tests...",
  "Deploying to server...",
  "Build completed successfully.",
];
